# -*- coding: utf-8 -*-
"""chatterbot.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B4FhniJDQLToG62eavx6JMfgfx27u9Yx
"""

pip install chatterbot

pip install chatterbot_corpus

import numpy as np

from chatterbot import ChatBot
chatbot = ChatBot("Ron Obvious")

chatbot

from chatterbot.trainers import ListTrainer
conversation = [
"My name is arun ahirwar"
"Hello",
"Hi there!",
"How are you doing?",
"I'm doing great.",
"That is good to hear",
"Thank you.",
"You're welcome."
]
trainer = ListTrainer(chatbot)
trainer.train(conversation)

trainer

response = chatbot.get_response("Good morning!")
print(response)

response = chatbot.get_response(input())
print(response)

response = chatbot.get_response(input())
print(response)

